a.exe n json_invalid/json_invalid/array_with_just_comma.json
a.exe n json_invalid/json_invalid/bad_escape.json
a.exe n json_invalid/json_invalid/bad_false.json
a.exe n json_invalid/json_invalid/bad_indentation.json
a.exe n json_invalid/json_invalid/bad_true.json
a.exe n json_invalid/json_invalid/comma.json
a.exe n json_invalid/json_invalid/duplicate_keys.json
a.exe n json_invalid/json_invalid/empty.json
a.exe n json_invalid/json_invalid/empty_file.json
a.exe n json_invalid/json_invalid/esc0.json
a.exe n json_invalid/json_invalid/esc1.json
a.exe n json_invalid/json_invalid/esc2.json
a.exe n json_invalid/json_invalid/esc3.json
a.exe n json_invalid/json_invalid/esc4.json
a.exe n json_invalid/json_invalid/ext-invalid-0001.json
a.exe n json_invalid/json_invalid/ext-invalid-0002.json
a.exe n json_invalid/json_invalid/fail_test_array_01.json
a.exe n json_invalid/json_invalid/fail01_EXCLUDE.json
a.exe n json_invalid/json_invalid/fail02.json
a.exe n json_invalid/json_invalid/fail03.json
#a.exe n json_invalid/json_invalid/fail04.json
#a.exe n json_invalid/json_invalid/fail05.json
#a.exe n json_invalid/json_invalid/fail06.json
#a.exe n json_invalid/json_invalid/fail07.json
#a.exe n json_invalid/json_invalid/fail08.json
#a.exe n json_invalid/json_invalid/fail09.json
#a.exe n json_invalid/json_invalid/fail1.json
#a.exe n json_invalid/json_invalid/fail10.json
#a.exe n json_invalid/json_invalid/fail11.json
#a.exe n json_invalid/json_invalid/fail12.json
#a.exe n json_invalid/json_invalid/fail13.json
#a.exe n json_invalid/json_invalid/fail14.json
#a.exe n json_invalid/json_invalid/fail15.json
#a.exe n json_invalid/json_invalid/fail16.json
#a.exe n json_invalid/json_invalid/fail17.json
#a.exe n json_invalid/json_invalid/fail18.json
#a.exe n json_invalid/json_invalid/fail18_EXCLUDE.json
#a.exe n json_invalid/json_invalid/fail19.json
#a.exe n json_invalid/json_invalid/fail2.json
#a.exe n json_invalid/json_invalid/fail20.json
#a.exe n json_invalid/json_invalid/fail21.json
#a.exe n json_invalid/json_invalid/fail22.json
#a.exe n json_invalid/json_invalid/fail23.json
#a.exe n json_invalid/json_invalid/fail24.json
#a.exe n json_invalid/json_invalid/fail25.json
#a.exe n json_invalid/json_invalid/fail26.json
#a.exe n json_invalid/json_invalid/fail27.json
#a.exe n json_invalid/json_invalid/fail28.json
#a.exe n json_invalid/json_invalid/fail29.json
#a.exe n json_invalid/json_invalid/fail3.json
#a.exe n json_invalid/json_invalid/fail30.json
#a.exe n json_invalid/json_invalid/fail31.json
#a.exe n json_invalid/json_invalid/fail32.json
#a.exe n json_invalid/json_invalid/fail33.json
#a.exe n json_invalid/json_invalid/fail4.json
#a.exe n json_invalid/json_invalid/fail5.json
#a.exe n json_invalid/json_invalid/fail6.json
#a.exe n json_invalid/json_invalid/fail7.json
#a.exe n json_invalid/json_invalid/fail8.json
#a.exe n json_invalid/json_invalid/fail9.json
#a.exe n json_invalid/json_invalid/float0.json
#a.exe n json_invalid/json_invalid/float1.json
#a.exe n json_invalid/json_invalid/invalid_utf8.json
#a.exe n json_invalid/json_invalid/invalid-0000.json
#a.exe n json_invalid/json_invalid/invalid-0001.json
#a.exe n json_invalid/json_invalid/invalid-0002.json
#a.exe n json_invalid/json_invalid/invalid-0003.json
#a.exe n json_invalid/json_invalid/invalid-0004.json
#a.exe n json_invalid/json_invalid/invalid-0005.json
#a.exe n json_invalid/json_invalid/invalid-0006.json
#a.exe n json_invalid/json_invalid/invalid-0007.json
#a.exe n json_invalid/json_invalid/invalid-0008.json
#a.exe n json_invalid/json_invalid/invalid-0009.json
#a.exe n json_invalid/json_invalid/invalid-0010.json
#a.exe n json_invalid/json_invalid/leading_zeroes.json
#a.exe n json_invalid/json_invalid/multiple_line_comment.json
#a.exe n json_invalid/json_invalid/no_quotes.json
#a.exe n json_invalid/json_invalid/no_tab_in_string.json
#a.exe n json_invalid/json_invalid/nostart.json
#a.exe n json_invalid/json_invalid/np_partial_bad.json
#a.exe n json_invalid/json_invalid/object0.json
#a.exe n json_invalid/json_invalid/object1.json
#a.exe n json_invalid/json_invalid/object2.json
#a.exe n json_invalid/json_invalid/object3.json
#a.exe n json_invalid/json_invalid/pass-but-fail-strict-1.json
#a.exe n json_invalid/json_invalid/pass-but-fail-strict-13.json
#a.exe n json_invalid/json_invalid/pass-but-fail-strict-18.json
#a.exe n json_invalid/json_invalid/pass-but-fail-strict-25.json
#a.exe n json_invalid/json_invalid/pass-but-fail-strict-27.json
#a.exe n json_invalid/json_invalid/pass-but-fail-strict-4.json
#a.exe n json_invalid/json_invalid/pass-but-fail-strict-9.json
#a.exe n json_invalid/json_invalid/single_line_comment.json
#a.exe n json_invalid/json_invalid/start_boolean.json
#a.exe n json_invalid/json_invalid/start_double.json
#a.exe n json_invalid/json_invalid/start_number.json
#a.exe n json_invalid/json_invalid/start_string.json
#a.exe n json_invalid/json_invalid/string_invalid_escape.json
#a.exe n json_invalid/json_invalid/string_invalid_hex_char.json
#a.exe n json_invalid/json_invalid/string_with_invalid_newline.json
#a.exe n json_invalid/json_invalid/trailing_comma.json
#a.exe n json_invalid/json_invalid/trucated_key.json
#a.exe n json_invalid/json_invalid/trucated_key_single_quote.json
#a.exe n json_invalid/json_invalid/trucated_value.json
#a.exe n json_invalid/json_invalid/trucated_value_single_quote.json
#a.exe n json_invalid/json_invalid/utf8_1.json
#a.exe n json_invalid/json_invalid/utf8_2.json
#a.exe n json_invalid/json_invalid/utf8_3.json
